title: Bemo2 Framework
email: bemo@cantierecreativo.net
description: >- # this means to ignore newlines until "baseurl:"
  The new jekyll single page to describe Bemo2
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://cantierecreativo.github.io/bemo" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cantierecreativo

# Build settings
markdown: kramdown
source: source
destination: _site
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

exclude:
  - node_modules
