source "https://rubygems.org"

gem "jekyll", "~> 3.8.5"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

gem "rake", "~>10.5"
gem "json", "~> 2"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "bourbon", "~>4.3"
  gem "pygments.rb"
  gem "jekyll-compose"
  gem "kramdown"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?

